server:
  port: 8060
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/barbershop?createDatabaseIfNotExist=true
    username: iuri
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update